### ISSUE TITLE
EmulationStation freeze when starting a game on Batocera 33 before video preview starts

### ISSUE THREAD

**Issue by melomitru** [pajarorrojo/es-theme-PlayStation-X#8]
EmulationStation freeze when I start a game on Batocera 33 before video preview starts and need to force power off.
For example, if I scroll games and I press X a few instant before video game preview starts, Emulation Station Freeze. Only video, music continues playing.
System Used:
Intel Core i7 (7500U)
4Gb RAM
Nvidia 740M

Nvidia driver enabled on Batocera.

**Comment by pajarorrojo** [comment]
Thanks for using ps-x theme. Your problem is not directly related to the theme, try to disable "POWER SAVER MODES", increase the VRAM size or activate the interface preload options, all this options are in the system configuration, but If you have done all this and the problem persists, report it on the batocera channel on discord or forum, maybe it's a problem related to the Nvidia drivers.

Regards
